services:
  db:
    container_name: database
    image: postgres
    environment:
      POSTGRES_PASSWORD: supercool
      POSTGRES_DB: esigtask
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d esigtask'" ]
      interval: 10s
      timeout: 3s
      retries: 3
  back:
    container_name: server
    build: .
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: database
    depends_on:
      db:
        condition: service_healthy